version: '3.9'

services:
  web:
    build:
      context: ./django
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
          condition: service_healthy

  db:
    image: postgres:14
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      web:
        condition: service_started

volumes:
  postgres_data:
